Fixed pdb error. exit() -> sys.exit()
An error was caused when __init__.py was invoked from the command line
and pdb was given as the module. This resulted in a
`ValueError: I/O operation on closed file` when cv2 is not installed.

An error message is also given saying that cv2 or ffmpeg failed, and to
please reinstall. However, that is buried in the error messages.

This was fixed by changing exit() on error of no cv2 to sys.exit().
This change prevents the site module from closing the input stream, thus
breaking pdb.

Here is the given traceback. File paths have been shortened to be more
brief and not give personal information.

$ python -m pdb ./__init__.py
> ./__init__.py(34)<module>()
-> """
(Pdb) c
ImportError, cv2 or ffmpeg are not installed or corrupted.
Please reinstall.
The program exited via sys.exit(). Exit status:  1
> ./__init__.py(34)<module>()
-> """
Traceback (most recent call last):
  File
"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pdb.py",
line 1314, in main
    pdb._runscript(mainpyfile)
  File
"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pdb.py",
line 1233, in _runscript
    self.run(statement)
  File
"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/bdb.py",
line 400, in run
    exec cmd in globals, locals
  File "<string>", line 1, in <module>
  File "./__init__.py", line 34, in <module>
    """
  File "./__init__.py", line 34, in <module>
    """
  File
"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/bdb.py",
line 49, in trace_dispatch
    return self.dispatch_line(frame)
  File
"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/bdb.py",
line 67, in dispatch_line
    self.user_line(frame)
  File
"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pdb.py",
line 158, in user_line
    self.interaction(frame, None)
  File
"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pdb.py",
line 210, in interaction
    self.cmdloop()
  File
"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/cmd.py",
line 130, in cmdloop
    line = raw_input(self.prompt)
ValueError: I/O operation on closed file
(Pdb) Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program
>
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/cmd.py(130)cmdloop()
-> line = raw_input(self.prompt)
(Pdb) Traceback (most recent call last):
  File
"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py",
line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File
"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py",
line 72, in _run_code
    exec code in run_globals
  File
"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pdb.py",
line 1338, in <module>
    pdb.main()
  File
"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pdb.py",
line 1330, in main
    pdb.interaction(None, t)
  File
"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pdb.py",
line 210, in interaction
    self.cmdloop()
  File
"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/cmd.py",
line 130, in cmdloop
    line = raw_input(self.prompt)
ValueError: I/O operation on closed file